version: 2.0

jobs:
  build-test-go:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test ./...
  build-test-sol:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: sudo npm install -g truffle
      - run: npm install --save-dev cids chai truffle-assertions
      - run: truffle test

workflows:
  version: 2
  build-test:
    jobs:
      - build-test-go
      - build-test-sol
